version: "3.7"
services:
    mongodb_container:
        image: mysql8
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_DATABASE: apidb
        ports:
            - 3306:3306
